/** Canonical release genre and sub-genre names for seeding and lookup. */
export const RELEASE_GENRES_SEED: readonly { name: string; subGenres: readonly string[] }[] = [
  {
    name: 'Blues',
    subGenres: [
      'Acoustic Blues',
      'Chicago Blues',
      'Classic Blues',
      'Contemporary Blues',
      'Country Blues',
      'Delta Blues',
      'Electric Blues',
      'Folk Blues',
      'Jazz Blues',
      'Piano Blues',
      'Soul Blues',
    ] as const,
  },
  {
    name: "Children's Music",
    subGenres: ['Lullabies', 'Sing-Along'] as const,
  },
  {
    name: 'Classical',
    subGenres: [
      'Avant-Garde',
      'Baroque',
      'Chamber Music',
      'Choral',
      'Classical Crossover',
      'Early Music',
      'High Classical',
      'Impressionist',
      'Medieval',
      'Minimalism',
      'Modern Composition',
      'Opera',
      'Orchestral',
      'Renaissance',
      'Romantic',
      'Wedding Music',
    ] as const,
  },
  {
    name: 'Country',
    subGenres: [
      'Alternative Country',
      'Americana',
      'Bluegrass',
      'Contemporary Bluegrass',
      'Contemporary Country',
      'Country Gospel',
      'Honky Tonk',
      'Outlaw Country',
      'Progressive Bluegrass',
      'Traditional Bluegrass',
      'Traditional Country',
      'Urban Cowboy',
    ] as const,
  },
  {
    name: 'Dance',
    subGenres: [
      'Breakbeat',
      'Deep House',
      'Disco',
      'Downtempo',
      'Drum & Bass',
      'Dubstep',
      'Electro House',
      'Electronica',
      'Euro-Dance',
      'Hardcore',
      'Hardstyle',
      'House',
      'IDM/Experimental',
      'Jungle',
      'Techno',
      'Trance',
      'Trap',
    ] as const,
  },
  {
    name: 'Electronic',
    subGenres: ['Ambient', 'Downtempo', 'Electronica', 'IDM/Experimental', 'Industrial'] as const,
  },
  {
    name: 'Folk',
    subGenres: ['Alternative Folk', 'Contemporary Folk', 'Indie Folk', 'Traditional Folk'] as const,
  },
  {
    name: 'Hip-Hop/Rap',
    subGenres: [
      'Alternative Rap',
      'Bounce',
      'Dirty South',
      'East Coast Rap',
      'Gangsta Rap',
      'Hardcore Rap',
      'Hip-Hop',
      'Latin Rap',
      'Old School Rap',
      'Rap',
      'Underground Rap',
      'West Coast Rap',
    ] as const,
  },
  {
    name: 'Holiday',
    subGenres: [
      'Chanukah',
      'Christmas',
      "Christmas: Children's",
      'Christmas: Classic',
      'Christmas: Classical',
      'Christmas: Jazz',
      'Christmas: Modern',
      'Christmas: Pop',
      'Christmas: R&B',
      'Christmas: Religious',
      'Christmas: Rock',
      'Easter',
      'Halloween',
      'Holiday: Other',
      'Thanksgiving',
    ] as const,
  },
  {
    name: 'Jazz',
    subGenres: [
      'Afro-Cuban Jazz',
      'Avant-Garde Jazz',
      'Bebop',
      'Big Band',
      'Blue Note',
      'Contemporary Jazz',
      'Cool Jazz',
      'Crossover Jazz',
      'Dixieland',
      'Fusion',
      'Hard Bop',
      'Latin Jazz',
      'Mainstream Jazz',
      'Ragtime',
      'Smooth Jazz',
      'Trad Jazz',
    ] as const,
  },
  {
    name: 'Latin',
    subGenres: [
      'Alternativo & Rock Latino',
      'Argentine Tango',
      'Bachata',
      'Baladas y Boleros',
      'Bossa Nova',
      'Brazilian',
      'Contemporary Latin',
      'Flamenco',
      'Latin Jazz',
      'Mariachi',
      'Merengue',
      'Pop Latino',
      'Português',
      'Regional Mexicano',
      'Salsa y Tropical',
    ] as const,
  },
  {
    name: 'New Age',
    subGenres: ['Environmental', 'Healing', 'Meditation', 'Nature', 'Relaxation', 'Self-Help'] as const,
  },
  {
    name: 'Pop',
    subGenres: [
      'Adult Contemporary',
      'Britpop',
      'Bubblegum Pop',
      'Chamber Pop',
      'Dance-Pop',
      'Dream Pop',
      'Indie Pop',
      'J-Pop',
      'K-Pop',
      'Pop/Rock',
      'Power Pop',
      'Soft Rock',
      'Synthpop',
      'Teen Pop',
      'Traditional Pop Vocal',
    ] as const,
  },
  {
    name: 'R&B/Soul',
    subGenres: [
      'Contemporary R&B',
      'Disco',
      'Doo Wop',
      'Funk',
      'Motown',
      'Neo-Soul',
      'Quiet Storm',
      'Soul',
    ] as const,
  },
  {
    name: 'Reggae',
    subGenres: ['Dancehall', 'Dub', 'Lovers Rock', 'Ragga', 'Roots Reggae', 'Ska'] as const,
  },
  {
    name: 'Rock',
    subGenres: [
      'Acid Rock',
      'Adult Alternative',
      'Alternative Rock',
      'Arena Rock',
      'Blues-Rock',
      'British Invasion',
      'Death Metal/Black Metal',
      'Doom Metal',
      'Glam Rock',
      'Goth Rock',
      'Grunge',
      'Hair Metal',
      'Hard Rock',
      'Heavy Metal',
      'Indie Rock',
      'Jam Bands',
      'J-Rock',
      'Metal',
      'Noise Rock',
      'Pop-Punk',
      'Post-Punk',
      'Progressive Rock',
      'Psychedelic Rock',
      'Punk Rock',
      'Rock & Roll',
      'Rockabilly',
      'Roots Rock',
      'Singer/Songwriter',
      'Southern Rock',
      'Surf Rock',
      'Tex-Mex',
    ] as const,
  },
  {
    name: 'Singer/Songwriter',
    subGenres: [
      'Alternative Folk',
      'Contemporary Folk',
      'Contemporary Singer/Songwriter',
      'Folk-Rock',
      'New Acoustic',
      'Traditional Folk',
    ] as const,
  },
  {
    name: 'Soundtrack',
    subGenres: [
      'Foreign Cinema',
      'Movie Soundtrack',
      'Musicals',
      'Original Score',
      'TV Soundtrack',
      'Video Game Score',
    ] as const,
  },
  {
    name: 'Spoken Word',
    subGenres: ['Comedy', 'Poetry'] as const,
  },
  {
    name: 'Vocal',
    subGenres: ['A Cappella', 'Standards', 'Traditional Pop', 'Vocal Jazz', 'Vocal Pop'] as const,
  },
  {
    name: 'World',
    subGenres: [
      'Africa',
      'Afro-Beat',
      'Afro-Pop',
      'Asia',
      'Australia',
      'Cajun',
      'Caribbean',
      'Celtic',
      'Celtic Rock',
      'Central Asia',
      'Chinese',
      'Europe',
      'France',
      'French Pop',
      'German Folk',
      'German Pop',
      'Greece',
      'Hawaii',
      'Indian',
      'Indian Pop',
      'Japan',
      'Japanese Pop',
      'Jewish',
      'Middle East',
      'North America',
      'Polka',
      'South Africa',
      'South America',
      'Traditional Celtic',
      'Worldbeat',
      'Zydeco',
    ] as const,
  },
  {
    name: 'Christian & Gospel',
    subGenres: [
      'Christian Metal',
      'Christian Pop',
      'Christian Rap',
      'Christian Rock',
      'Gospel',
      'Praise & Worship',
      'Southern Gospel',
      'Traditional Gospel',
    ] as const,
  },
  {
    name: 'Inspirational',
    subGenres: ['Faith', 'Inspirational'] as const,
  },
] as const;
